name: Baseline Jekyll
timezone: America/Sao_Paulo
pygments: true
source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
exclude:     ['node_modules', 'Gruntfile.js', 'package.json', 'template-copy.html']
